/*
=============================================================================
* EDUCATIONAL WALKTHROUGH: AudioEngine.jsx — The Web Audio API
=============================================================================
*
* WHAT IS THE WEB AUDIO API?
* Most people play audio on the web by loading an MP3 file.
* The Web Audio API is different — it lets you GENERATE sounds mathematically
* inside the browser, with zero files to download.
*
* Think of it like a synthesizer built inside your browser.
*
* HOW "BROWN NOISE" WORKS (The Math Is Beautiful):
* Sound is just rapid variations in air pressure. "White noise" is completely
* random pressure changes across ALL frequencies (like TV static).
*
* "Brown noise" (also called Brownian noise) is generated by doing a "random
* walk" — each new sample is the previous sample PLUS a small random nudge.
* This naturally emphasizes low frequencies (deep rumble, rain, a waterfall).
* It is scientifically gentler on focus than white noise.
*
* The Web Audio API pipeline we create looks like this:
*
*   [Script Processor Node]  →  [Gain Node]  →  [Audio Destination (Speakers)]
*   (Generates Brown Noise)      (Controls Volume)   (Your actual headphones)
*
* HOW THE FADE WORKS:
* The Gain Node has a property called `gain.value` — it's a multiplier.
* 0 = silence. 1 = full volume.
* We use `gain.linearRampToValueAtTime()` to tell the browser:
* "Over the next 5 seconds, smoothly increase the gain from 0 to 0.3."
* The browser handles the interpolation — no timers needed from us.
*
=============================================================================
*/

import { useEffect, useRef, useCallback } from 'react';

const useAudioEngine = () => {
  // We use refs to hold the AudioContext and GainNode.
  // Refs are ideal for this because:
  //   1. They persist across renders (like an instance variable)
  //   2. Updating them does NOT trigger a re-render (we don't want the UI
  //      to flash every time the audio volume changes internally)
  const audioContextRef = useRef(null);
  const gainNodeRef = useRef(null);
  const sourceNodeRef = useRef(null);
  const isPlayingRef = useRef(false);

  // -- STEP 1: The Noise Generator --
  // A ScriptProcessorNode lets us write a JavaScript function that generates
  // audio buffer samples directly. For each chunk the browser needs,
  // it calls our `onaudioprocess` function.
  const createBrownNoiseSource = (audioContext) => {
    // 4096 is the "buffer size" — how many samples to generate each call.
    // Larger = less CPU strain, but potentially more latency.
    const bufferSize = 4096;
    const node = audioContext.createScriptProcessor(bufferSize, 1, 1);

    let lastOut = 0.0; // This is our "previous value" for the random walk.

    node.onaudioprocess = (e) => {
      // getChannelData gives us a writable Float32Array for the left channel (0)
      const output = e.outputBuffer.getChannelData(0);

      for (let i = 0; i < bufferSize; i++) {
        // The Brown Noise formula: next = last + random_nudge
        // We use (Math.random() * 2 - 1) to get a random number from -1 to +1.
        const white = Math.random() * 2 - 1;
        output[i] = (lastOut + (0.02 * white)) / 1.02;
        lastOut = output[i];
        // Multiply by 3.5 to boost volume to a reasonable level
        output[i] *= 3.5;
      }
    };

    return node;
  };

  // -- STEP 2: Start Audio with a Gentle Fade-In --
  const startAudio = useCallback(() => {
    if (isPlayingRef.current) return; // Guard: don't double-start

    // AudioContext cannot be created until a user has interacted with the 
    // page (browser security rule called "Autoplay Policy"). Since this is 
    // triggered by a button click, we are safe to create it here.
    const audioContext = new (window.AudioContext || window.webkitAudioContext)();
    const gainNode = audioContext.createGain();

    // -- The Fade: Start at 0 volume, ramp to 0.3 over 5 seconds --
    gainNode.gain.setValueAtTime(0, audioContext.currentTime);
    gainNode.gain.linearRampToValueAtTime(0.3, audioContext.currentTime + 5);

    const source = createBrownNoiseSource(audioContext);

    // Wire the pipeline: source → gain → speakers
    source.connect(gainNode);
    gainNode.connect(audioContext.destination);

    // Save refs so we can stop/clean up later
    audioContextRef.current = audioContext;
    gainNodeRef.current = gainNode;
    sourceNodeRef.current = source;
    isPlayingRef.current = true;
  }, []);

  // -- STEP 3: Stop Audio with a Gentle Fade-Out --
  const stopAudio = useCallback(() => {
    if (!isPlayingRef.current || !audioContextRef.current) return;

    const audioContext = audioContextRef.current;
    const gainNode = gainNodeRef.current;

    // Fade out over 2 seconds, then close the audio context entirely
    gainNode.gain.linearRampToValueAtTime(0, audioContext.currentTime + 2);

    // After 2.1 seconds (a little after the fade finishes), close and clean up
    setTimeout(() => {
      try {
        sourceNodeRef.current?.disconnect();
        gainNodeRef.current?.disconnect();
        audioContextRef.current?.close();
      } catch { /* ignore cleanup errors */ }

      audioContextRef.current = null;
      gainNodeRef.current = null;
      sourceNodeRef.current = null;
      isPlayingRef.current = false;
    }, 2100);
  }, []);

  // -- STEP 4: Cleanup on component unmount --
  useEffect(() => {
    return () => stopAudio();
  }, [stopAudio]);

  return { startAudio, stopAudio, isPlayingRef };
};

export default useAudioEngine;
